sudo: required

language: php

php:
  - '7.2'

services:
  - docker

before_script: composer install

script:
  - docker build -t tec/internship-reg-panitia .
  - docker tag tec/internship-reg-panitia node2.didithilmy.com/tec/internship-reg-panitia
  - docker push node2.didithilmy.com/tec/internship-reg-panitia
